import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

/**
 * IMPORTANT — verifiability policy
 *
 * Every entry in this list is a SUMMARY written by UltraCem with reference to a
 * real Colombian standard (NSR-10, NTC, RES 0549/2015, AIS-180, etc.). The codes
 * are real. The `content` text is NOT a literal quote from the official document
 * — it's a maestro-friendly paraphrase. To make this honest with our users:
 *
 * - `articleRef` points to the specific article/section inside the source so a
 *   reader can cross-check the claim (e.g. "Título C, §C.4.2").
 * - `verbatim` is false for every entry below. Setting it to `true` is a promise
 *   that the `content` is copied word-for-word from the official document.
 * - `source` MUST be a URL verified to return HTTP 200. Many NTC standards have
 *   no free public PDF — in that case use the issuer's institutional page only.
 *   NEVER invent product paths or deep links you haven't checked.
 *
 * The UI at /normas/[code] reads these fields and renders a disclaimer when
 * `verbatim` is false. Do not flip `verbatim` to true without pasting the exact
 * official text into `content`.
 */

const standards = [
  {
    code: 'NSR-10-C.4.2',
    title: 'Concreto estructural — Resistencia mínima',
    category: 'concrete',
    region: 'todos',
    structureType: 'slab',
    content: 'El concreto estructural para losas y columnas debe tener una resistencia mínima a compresión de 21 MPa (3000 PSI) a los 28 días según NSR-10 Título C. En zonas de amenaza sísmica alta se exige mínimo 28 MPa (4000 PSI).',
    implication: 'Tu losa o columna debe soportar al menos 3000 PSI (21 MPa) a los 28 días. Si estás en zona sísmica alta, el mínimo sube a 4000 PSI para garantizar la seguridad estructural.',
    articleRef: 'NSR-10 Título C, Capítulo C.4, §C.4.2 (Requisitos de mezclas de concreto)',
    verbatim: false,
    parameters: { minPsi: 3000, seismicMinPsi: 4000, cureDays: 28 },
    source: 'https://www.minvivienda.gov.co/taxonomy/term/2753',
    tags: ['resistencia', 'psi', 'estructural', 'sismo'],
    priority: 10,
  },
  {
    code: 'NSR-10-C.4.5',
    title: 'Relación agua/cemento máxima para durabilidad',
    category: 'concrete',
    region: 'todos',
    structureType: null,
    content: 'Para concreto expuesto a sulfatos o ambientes marinos, la relación agua/cemento máxima permitida es 0.45. En clima cálido (>30 °C) se recomienda reducir a 0.40 para evitar fisuración por secado rápido.',
    implication: 'No uses demasiada agua en la mezcla. En zona costera o con calor intenso, menos agua evita que el concreto se agriete antes de endurecerse.',
    articleRef: 'NSR-10 Título C, Capítulo C.4, §C.4.3 (Requisitos especiales por durabilidad)',
    verbatim: false,
    parameters: { maxWaterCementRatio: 0.45, warmClimateRatio: 0.40 },
    source: 'https://www.minvivienda.gov.co/taxonomy/term/2753',
    tags: ['agua', 'cemento', 'durabilidad', 'mezcla'],
    priority: 9,
  },
  {
    code: 'NSR-10-H.4.2',
    title: 'Requisitos para estructuras en zona costera',
    category: 'concrete',
    region: 'caribe',
    structureType: null,
    content: 'Estructuras expuestas a ambiente marino (salitre) deben usar concreto de mínimo 3000 PSI con cemento resistente a sulfatos (Tipo MS o HS). El recubrimiento mínimo del acero de refuerzo es 7.5 cm para elementos en contacto con el suelo y 5 cm para el resto.',
    implication: 'En la costa el salitre destruye el concreto débil. Por eso se exige mínimo 3000 PSI y cemento tipo MS o HS para que tu estructura dure.',
    articleRef: 'NSR-10 Título H, §H.4 (Cimentaciones en ambiente marino) y Título C, §C.7.7 (Recubrimiento mínimo)',
    verbatim: false,
    parameters: { minPsi: 3000, minCoverCm: 7.5, cementType: 'MS' },
    source: 'https://www.minvivienda.gov.co/taxonomy/term/2753',
    tags: ['costa', 'salitre', 'marino', 'sulfatos', 'caribe'],
    priority: 10,
  },
  {
    code: 'NSR-10-D.3.1',
    title: 'Mampostería — Mortero de pega para muros',
    category: 'masonry',
    region: 'todos',
    structureType: 'wall',
    content: 'Para mampostería estructural, el mortero de pega debe cumplir resistencia mínima Tipo M (17.5 MPa). Para muros no estructurales se permite Tipo N (5.2 MPa). El espesor de juntas debe ser 1.0-1.5 cm.',
    implication: 'Si el muro soporta carga (estructural), usa mortero Tipo M. Si es división, basta con Tipo N. Juntas de 1 a 1.5 cm evitan grietas y desplomes.',
    articleRef: 'NSR-10 Título D, Capítulo D.3, §D.3.4 (Mortero de pega) — clasificación según NTC 3329',
    verbatim: false,
    parameters: { minMpaM: 17.5, minMpaN: 5.2, jointCm: 1.0 },
    source: 'https://www.minvivienda.gov.co/taxonomy/term/2753',
    tags: ['muro', 'bloque', 'mortero', 'pega', 'mampostería'],
    priority: 8,
  },
  {
    code: 'NSR-10-H.5.2',
    title: 'Curado mínimo según clima',
    category: 'concrete',
    region: 'todos',
    structureType: null,
    content: 'El curado húmedo continuo debe mantenerse mínimo 7 días. En clima cálido-seco (Caribe, >30 °C) se requiere mínimo 10 días con protección solar (lonas, plástico) para evitar fisuración térmica.',
    implication: 'Moja el concreto mínimo 7 días. En el Caribe, 10 días con sombra o plástico para que el calor no lo agriete antes de agarrar fuerza.',
    articleRef: 'NSR-10 Título C, Capítulo C.5, §C.5.11 (Curado) — guía complementaria ACI 308R',
    verbatim: false,
    parameters: { minCuringDaysNormal: 7, minCuringDaysWarm: 10 },
    source: 'https://www.minvivienda.gov.co/taxonomy/term/2753',
    tags: ['curado', 'clima', 'calor', 'fisuración'],
    priority: 7,
  },
  {
    code: 'NTC-121',
    title: 'Especificaciones del cemento Portland',
    category: 'concrete',
    region: 'todos',
    structureType: null,
    content: 'La NTC 121 (equivalente ASTM C150) especifica los Tipos de cemento: GU (uso general), HE (alta resistencia temprana), MS (moderada resistencia a sulfatos), HS (alta resistencia a sulfatos). Para zona costera se recomienda Tipo MS como mínimo.',
    implication: 'No todos los cementos sirven para todo. En la costa, mínimo Tipo MS para que el salitre no lo degrade. En obra normal, Tipo GU está bien.',
    articleRef: 'NTC 121:2014 — Cemento hidráulico. Especificaciones de desempeño (homóloga ASTM C1157)',
    verbatim: false,
    parameters: { types: ['GU', 'HE', 'MS', 'HS'] },
    source: 'https://www.icontec.org/normalizacion/',
    tags: ['NTC', 'cemento', 'tipos', 'Portland'],
    priority: 7,
  },
  {
    code: 'NTC-4027',
    title: 'Morteros de pega para mampostería',
    category: 'masonry',
    region: 'todos',
    structureType: 'wall',
    content: 'La NTC 4027 clasifica los morteros de pega por resistencia: M (17.5 MPa), S (12.5 MPa), N (5.2 MPa), O (2.5 MPa). Para muros de carga en zonas sísmicas se requiere mínimo Tipo S.',
    implication: 'Si el muro carga peso y hay riesgo de sismo, mínimo mortero Tipo S. Más bajo y puede fallar en un movimiento fuerte.',
    articleRef: 'NTC 3329:2004 — Especificación para morteros de mampostería (clasificación tipos M/S/N/O); ver también NSR-10 D.3.4',
    verbatim: false,
    parameters: { minSeismic: 'Tipo S (12.5 MPa)' },
    source: 'https://www.icontec.org/normalizacion/',
    tags: ['mortero', 'pega', 'mampostería', 'sismo'],
    priority: 8,
  },
  {
    code: 'NTC-673',
    title: 'Ensayo de resistencia a compresión de concretos',
    category: 'concrete',
    region: 'todos',
    structureType: null,
    content: 'La resistencia se mide en cilindros de 15x30 cm curados 28 días. El ensayo debe seguir NTC 673. Para obra, se toman mínimo 2 cilindros por cada 50 m³ de concreto colocado.',
    implication: 'Para saber si tu concreto quedó bueno, se hacen cilindros de prueba. Mínimo 2 por cada 50 m³ para controlar calidad en obra.',
    articleRef: 'NTC 673 — Ensayo de resistencia a la compresión de especímenes cilíndricos de concreto (ASTM C39). Frecuencia de muestreo: NSR-10 C.5.6.2',
    verbatim: false,
    parameters: { cylinderSize: '15x30 cm', samplesPerVolume: 2 },
    source: 'https://www.icontec.org/normalizacion/',
    tags: ['ensayo', 'compresión', 'cilindro', 'control'],
    priority: 5,
  },
  {
    code: 'RES-0549-2015',
    title: 'Guía de Construcción Sostenible — Ahorro de Agua y Energía',
    category: 'sustainability',
    region: 'todos',
    structureType: null,
    content: 'Según la Resolución 0549 de 2015 del Ministerio de Vivienda, toda construcción nueva debe implementar medidas de ahorro de agua (mín. 40% vs línea base) y energía (mín. 20%). Para maestros de obra: usar curado eficiente, mezclas con menor demanda de agua, y preferir materiales de producción local.',
    implication: 'La ley exige ahorrar agua y energía en obra nueva. Menos desperdicio de agua en el curado y materiales de cerca reducen costos y multas.',
    articleRef: 'Res. 0549/2015 (sustituida por Res. 0194/2025) — Guía construcción sostenible, Anexo 1',
    verbatim: false,
    parameters: { waterSavingMinPercent: 40, energySavingMinPercent: 20 },
    source: 'https://minvivienda.gov.co/normativa/resolucion-0194-2025',
    tags: ['sostenibilidad', 'agua', 'energía', 'obligatorio'],
    priority: 8,
  },
  {
    code: 'CASA-COL-2023',
    title: 'Certificación CASA Colombia — Criterios para el trópico',
    category: 'sustainability',
    region: 'caribe',
    structureType: null,
    content: 'El sistema CASA Colombia del CCCS otorga certificación de construcción sostenible adaptada al trópico. Para el Caribe: ventilación natural, protección solar en fachadas, materiales de origen local (radio < 500 km), y manejo de aguas lluvias.',
    implication: 'Si quieres una obra sostenible en el Caribe, usa materiales de menos de 500 km de distancia. Menos transporte = menos CO₂ y más economía local.',
    articleRef: 'Programa CASA Colombia — criterios de certificación sostenible (CCCS)',
    verbatim: false,
    parameters: { localMaterialRadiusKm: 500 },
    source: 'https://www.cccs.org.co',
    tags: ['sostenibilidad', 'certificación', 'CASA', 'caribe'],
    priority: 6,
  },
  {
    code: 'NTC-6112-2021',
    title: 'Etiquetas Ambientales Tipo I para cementos y concretos',
    category: 'sustainability',
    region: 'todos',
    structureType: null,
    content: 'La NTC 6112 establece criterios de sello ambiental colombiano para cementos. Un cemento de bajo carbono debe tener huella < 0.75 kg CO₂/kg de cemento. UltraCem tiene productos que cumplen este estándar.',
    implication: 'Un cemento con menos de 0.75 kg de CO₂ por kg tiene sello ambiental colombiano. Elegirlo baja la huella de tu obra y puede facilitar permisos.',
    articleRef: 'NTC 6112 — Etiquetas ambientales Tipo I (Evalcon / ICONTEC)',
    verbatim: false,
    parameters: { lowCarbonThreshold: 0.75 },
    source: 'https://www.icontec.org/validacion-y-verificacion/',
    tags: ['sostenibilidad', 'CO2', 'sello_ambiental'],
    priority: 6,
  },
  {
    code: 'NSR-10-A.3.2',
    title: 'Zonificación sísmica de Colombia',
    category: 'structural',
    region: 'todos',
    structureType: null,
    content: 'Colombia se divide en zonas de amenaza sísmica: Alta (costa Pacífica, Santanderes, Eje Cafetero), Intermedia (Caribe, Andina central), y Baja (Llanos, Amazonía). En zona alta se exigen diseños sismo-resistentes con confinamiento completo.',
    implication: 'Si estás en costa Pacífica o Eje Cafetero, tu construcción debe ser más resistente a temblores. Eso significa más refuerzo y concreto de mayor calidad.',
    articleRef: 'NSR-10 Título A, Capítulo A.3 (Zonificación sísmica de Colombia)',
    verbatim: false,
    parameters: { zones: ['alta', 'intermedia', 'baja'] },
    source: 'https://www.minvivienda.gov.co/taxonomy/term/2753',
    tags: ['sismo', 'zona', 'amenaza', 'resistencia'],
    priority: 9,
  },
  {
    code: 'NSR-10-E.2.1',
    title: 'Revoques y pañetes — Espesores mínimos',
    category: 'plaster',
    region: 'todos',
    structureType: 'plaster',
    content: 'El espesor mínimo de revoque para muros interiores es 1.5 cm y para exteriores 2.0 cm. En zona costera con exposición al salitre, se recomienda 2.5 cm con impermeabilizante integral en la mezcla.',
    implication: 'Revoque interior mínimo 1.5 cm, exterior 2 cm. En la costa, 2.5 cm con impermeabilizante para que el salitre no traspase la pared.',
    articleRef: 'NSR-10 Título E, §E.2 (Revoques y pañetes — espesores mínimos)',
    verbatim: false,
    parameters: { minInteriorCm: 1.5, minExteriorCm: 2.0, coastalCm: 2.5 },
    source: 'https://www.minvivienda.gov.co/taxonomy/term/2753',
    tags: ['revoque', 'pañete', 'espesor', 'acabado'],
    priority: 5,
  },
  {
    code: 'AIS-180-2015',
    title: 'Manual de vivienda sismo resistente',
    category: 'structural',
    region: 'todos',
    structureType: null,
    content: 'La Asociación de Ingeniería Sísmica (AIS) publica el manual de construcción sismo resistente para viviendas de 1 y 2 pisos. Incluye especificaciones de confinamiento de muros, vigas de amarre, y refuerzo mínimo en columnas.',
    implication: 'En viviendas de 1 o 2 pisos, confina muros con vigas y columnas. Eso evita que se desplomen en un sismo, aunque sean pequeñas.',
    articleRef: 'Documento AIS-180 — Manual de vivienda sismo resistente (1 y 2 pisos)',
    verbatim: false,
    parameters: {},
    source: 'https://www.asosismica.org.co',
    tags: ['sismo', 'vivienda', 'manual', 'confinamiento'],
    priority: 7,
  },
  {
    code: 'NSR-10-C.10.6',
    title: 'Recubrimiento mínimo del acero de refuerzo',
    category: 'concrete',
    region: 'todos',
    structureType: 'column',
    content: 'El recubrimiento mínimo del acero en columnas es 4 cm para interiores y 5 cm para exteriores. En zona costera con exposición marina se aumenta a 7 cm todos los elementos.',
    implication: 'El concreto debe cubrir el hierro de la columna: 4 cm adentro, 5 cm afuera. En la costa, 7 cm para que el salitre no corroa el acero.',
    articleRef: 'NSR-10 Título C, §C.7.7 (Recubrimiento mínimo del acero de refuerzo)',
    verbatim: false,
    parameters: { interiorCm: 4, exteriorCm: 5, coastalCm: 7 },
    source: 'https://www.minvivienda.gov.co/taxonomy/term/2753',
    tags: ['recubrimiento', 'acero', 'columna', 'corrosión'],
    priority: 8,
  },
  {
    code: 'CCCS-GUIA-01',
    title: 'Guía CCCS de materiales de bajo carbono',
    category: 'sustainability',
    region: 'todos',
    structureType: null,
    content: 'El Consejo Colombiano de Construcción Sostenible recomienda: usar cementos con adiciones (ceniza volante, escoria) que reducen hasta 30% el CO₂, preferir agregados de canteras cercanas (<100 km), y optimizar el diseño de mezcla para usar menos cemento sin sacrificar resistencia.',
    implication: 'Cementos con ceniza volante o escoria bajan el CO₂ hasta 30%. Agregados de menos de 100 km ahorran transporte. Menos cemento bien dosificado = menos costo y menos huella.',
    articleRef: 'Guía CCCS — Materiales de bajo carbono en construcción',
    verbatim: false,
    parameters: { maxTransportKm: 100, co2ReductionPercent: 30 },
    source: 'https://www.cccs.org.co',
    tags: ['sostenibilidad', 'CO2', 'bajo_carbono', 'CCCS'],
    priority: 6,
  },
  {
    code: 'NSR-10-C.8.1',
    title: 'Dosificación de mezclas de concreto',
    category: 'concrete',
    region: 'todos',
    structureType: 'slab',
    content: 'Para 3000 PSI (21 MPa) la dosificación típica es 350 kg cemento/m³. Para 4000 PSI (28 MPa) es 420 kg cemento/m³. La proporción cemento:arena:grava recomendada es 1:2:3 para elementos estructurales.',
    implication: 'Esta es la tabla base de la NSR-10: 350 kg de cemento por cada metro cúbico para 3000 PSI. Más resistencia = más cemento, pero nunca fuera de proporción 1:2:3 para no debilitar la mezcla.',
    articleRef: 'Referencia técnica de obra (no es tabla literal NSR-10) — ver NSR-10 C.4.2 para resistencia exigida',
    verbatim: false,
    parameters: { psi3000Cement: 350, psi4000Cement: 420, ratio: '1:2:3' },
    source: 'https://www.minvivienda.gov.co/taxonomy/term/2753',
    tags: ['dosificación', 'mezcla', 'proporción', 'cemento'],
    priority: 10,
  },
  {
    code: 'NSR-10-TIT-J',
    title: 'Requisitos de protección contra incendios',
    category: 'safety',
    region: 'todos',
    structureType: null,
    content: 'El Título J de la NSR-10 exige que elementos estructurales en edificaciones tengan resistencia al fuego según el uso: R120 para vivienda multifamiliar (>3 pisos), R60 para vivienda unifamiliar. El concreto tiene excelente resistencia al fuego por naturaleza.',
    implication: 'Edificios de más de 3 pisos deben resistir fuego 120 minutos; casas unifamiliares 60 minutos. El concreto cumple esto solo si se dosifica y cura bien.',
    articleRef: 'NSR-10 Título J (Protección contra incendios — resistencia al fuego)',
    verbatim: false,
    parameters: { fireRatingR: [60, 120] },
    source: 'https://www.minvivienda.gov.co/taxonomy/term/2753',
    tags: ['incendio', 'seguridad', 'fuego', 'resistencia'],
    priority: 5,
  },
  {
    code: 'CAMACOL-BP-01',
    title: 'Buenas prácticas para concreto en clima cálido (Camacol)',
    category: 'concrete',
    region: 'caribe',
    structureType: null,
    content: 'Camacol recomienda para el Caribe: humedecer los agregados antes de mezclar, usar hielo en el agua de mezcla si la temperatura supera 35 °C, vaciar en horas de menor temperatura (madrugada o noche), y proteger la mezcla fresca con polietileno.',
    implication: 'En el Caribe, el calor acelera el fraguado y puede agrietar el concreto. Humedece agregados, vierte de noche y cubre con plástico para controlar temperatura.',
    articleRef: 'Buenas prácticas Camacol — concreto en clima cálido (guía gremial, no norma legal)',
    verbatim: false,
    parameters: { maxTempC: 35, coolingMethod: 'hielo' },
    source: 'https://camacol.co',
    tags: ['calor', 'clima', 'mezcla', 'caribe', 'Camacol'],
    priority: 7,
  },
  {
    code: 'NTC-2289',
    title: 'Barras de acero para refuerzo de concreto',
    category: 'structural',
    region: 'todos',
    structureType: 'column',
    content: 'La NTC 2289 especifica las barras de acero corrugado para refuerzo. Varillas #3 (3/8") mínimo para columnas en vivienda, y #4 (1/2") para vigas. En zona costera se recomienda acero recubierto con epóxico para prevenir corrosión.',
    implication: 'Columnas de vivienda: mínimo varilla #3 (3/8"). En la costa, acero con epóxico evita que el salitre lo oxide por dentro del concreto.',
    articleRef: 'NTC 2289 — Barras de acero corrugado para refuerzo de concreto',
    verbatim: false,
    parameters: { minColumnBar: '#3', minBeamBar: '#4' },
    source: 'https://www.icontec.org/normalizacion/',
    tags: ['acero', 'refuerzo', 'varilla', 'columna'],
    priority: 6,
  },
];

async function main() {
  console.log('Seeding Colombian construction standards...');

  await prisma.constructionStandard.deleteMany();

  for (const standard of standards) {
    await prisma.constructionStandard.create({ data: standard });
  }

  const count = await prisma.constructionStandard.count();
  console.log(`Successfully seeded ${count} construction standards`);
}

main()
  .catch((e) => {
    console.error('Seed error:', e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
